name: javascript

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14, 15, 16, 17]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test